[agent]
  interval = "1s"
  flush_interval = "1s"
  debug = true

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  
  topics = ["tfgsenda/vlizmar/nodo1"]
  #topics = ["#"]
  
  data_format = "json"
  
  json_string_fields = ["clase"]
  
  json_name_key = "clase" 

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "mi_token_secreto_123"
  organization = "portenta_org"
  bucket = "fomo_data"